[package]
name = "rust-lox"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Fred Roth"]
description = "An interpreter for the Lox language (http://craftinginterpreters.com/)"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
miette = { version = "6.0.1", features = ["fancy", "syntect-highlighter"] }
phf = { version = "0.11.2", features = ["macros"] }
thiserror = "1.0.56"
strum = { version = "0.26", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.79"
assert_matches = "1.5"
