[package]
name = "rust-lox"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Fred Roth"]
description = "An interpreter for the Lox language (http://craftinginterpreters.com/)"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
